# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'WeatherIconsCocoapodsExample' do
	pod 'WeatherIconsKit', :path => '../WeatherIconsKit.podspec'
end

target 'WeatherIconsCocoapodsExampleTests' do

end

